// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3467.robot;
    

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
	//Pneumatics:
	public final static int pcmId = 0;
	public final static int intakeSolenoidPort = 0;
	
	//Drive Base Motors:
	public final static int frontRightMotorPort = 0;
	public final static int rearRightMotorPort = 1;
	public final static int frontLeftMotorPort = 2;
	public final static int rearLeftMotorPort = 3;
	
	//Intake Motors:
	public final static int leftIntakeMotorPort = 4;
	public final static int rightIntakeMotorPort = 5;
	
	
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
